### ISSUE TITLE
Found a japanese error

### ISSUE THREAD

**Issue by adriansalgadoa** [Martyn96/SpeechBot#1]
Wrote "/s coiporu cosmicoru" and it returned an empty file. Thought it wouldn't process it so tried with each word individually and it worked, then tried again and it returned the correct sound file after a while.

It wasn't a connection error because I tried with other words and they did work.

**Comment by martijnrondeel** [comment]
Please describe the error.

**Comment by martijnrondeel** [comment]
I've had this issue a few times too, sometimes Google's API returns back nothing (try setting language to chinese and doing /speech zhzhzhzhzhhzzhh for example) but when breaking down the sentence in smaller parts it does work. Not much the bot can do about this small issue though.
